 language: ruby
 rvm: "2.1.1"
 bundler_args: --without production
# uncomment this line if your project needs to run something other than `rake`:
 script: 
 - cd rails/EduWords
 - bundle install
 - bundle exec rspec spec
