source 'https://rubygems.org'

gem 'rails', '4.0.3'

group :development do
  gem 'sqlite3', '1.3.8'
  gem 'quiet_assets'
end

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '3.1.0'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'redcarpet', '3.1.1'
gem 'validates_email_format_of'

group :development, :test do
  gem 'rspec-rails'
end

group :test do
  gem 'selenium-webdriver', '2.39.0'
  gem 'capybara', '2.2.1'
  gem "minitest"
end

gem 'sass-rails', '4.0.1'
gem 'bootstrap-sass', '3.1.1.0'